# OpenNMT-py config for English -> Amharic (MANUAL BPE VERSION)

data:
  train:
    path_src: /kaggle/working/mt/train.bpe.en
    path_tgt: /kaggle/working/mt/train.bpe.am

  valid:
    path_src: /kaggle/working/mt/dev.bpe.en
    path_tgt: /kaggle/working/mt/dev.bpe.am


# -----------------------------
# Vocab building
# -----------------------------
save_data: /kaggle/working/mt/data

src_vocab: /kaggle/working/mt/data.vocab.src
tgt_vocab: /kaggle/working/mt/data.vocab.tgt


# -----------------------------
# Model (matches paper)
# -----------------------------
encoder_type: rnn
decoder_type: rnn
rnn_type: LSTM

enc_layers: 6
dec_layers: 6

hidden_size: 512
word_vec_size: 512
global_attention: general


# -----------------------------
# Training (FIXED)
# -----------------------------
# -----------------------------
# Training (paper exact)
# -----------------------------
train_steps: 25000
save_checkpoint_steps: 4000
valid_steps: 1000

batch_type: tokens
batch_size: 4096
accum_count: 1

normalization: tokens
label_smoothing: 0.1

optim: adam
learning_rate: 0.0005
dropout: 0.3
max_grad_norm: 5
seed: 42

# -----------------------------
# IMPORTANT FIX
# -----------------------------
copy_attn: true


# -----------------------------
# Inference
# -----------------------------
beam_size: 5
